# Generated by Django 3.2.3 on 2022-02-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(max_length=1000)),
                ('about_work', models.CharField(max_length=10000)),
                ('choose', models.CharField(choices=[('given', 'Given'), ('taken', 'Taken')], max_length=15)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upload', 'Upload')], max_length=20)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
